
import type { Metadata } from "next";



const About = () => {
    return <div>About</div>;
  };
  
  export default About;
  

  export const metadata: Metadata = {
    title: "About",
    description: "Generated by create next app",
  };
  